# Generated by Django 5.2.6 on 2025-09-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adverseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crfs', to='core.study')),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('study', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CRFField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('choice', 'Choice')], default='text', max_length=12)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.crf')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('crf', 'code')},
            },
        ),
    ]
