# Generated by Django 5.2.6 on 2025-09-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crf_crffield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.crffield')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.visit')),
            ],
            options={
                'ordering': ['visit_id', 'field_id'],
                'unique_together': {('visit', 'field')},
            },
        ),
    ]
